import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li className="cursor-pointer">
          <Link to="/cart">Cart</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/homepage">Homepage</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/shop">Shop</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/shopdetaildescription">ShopDetailDescription</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/detailreview">DetailReview</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/checkout">Checkout</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/team">Team</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/blog">Blog</Link>
        </li>
        <li>
          <Link to="/blogdetail">BlogDetail</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/contactus">Contactus</Link>
        </li>
        <li className="cursor-pointer">
          <Link to="/aboutus">Aboutus</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
